version: '3.7'

services:
  consul:
    image: consul:1.9.0
    container_name: consul
    restart: always
    networks:
      - becomfy
    ports:
      - 8500:8500

  rabbitmq:
    image: rabbitmq:3.8.9-management
    networks:
      - becomfy
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - becomfy
    ports: 
      - 27017:27017
    volumes:
      - mongo:/data/db

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    networks: 
      - becomfy
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - becomfy

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
    networks:
      - becomfy

networks:
  becomfy:
    name: becomfy-network

volumes:
  rabbitmq:
    driver: local
  mongo:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
