version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    restart: always
    networks:
      - becomfy
    ports:
      - 8500:8500

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - becomfy
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - becomfy
    ports: 
      - 27017:27017
      volumes:
        - mongo:/data/db

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    networks: 
      - becomfy
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

networks:
  becomfy:
    name: becomfy-network

volumes:
  rabbitmq:
    driver: local
  mongo:
    driver: local
